root = "."
tmp_dir = "build"

[build]
  cmd = "go build -o ./build/app"
  bin = "build/app"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "build", "node_modules"]
  exclude_file = []
  follow_symlink = true
  exclude_regex = ["_test\\.go"]
  delay = 1000 # milliseconds
  stop_on_error = true

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
  error = "red"

[misc]
  clean_on_exit = true